version: '3.8'

services:
  prometheuscycle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheuscycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
