# fly.toml app configuration file generated for apifullcycle on 2024-07-25T01:20:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apifullcycle'
primary_region = 'gru'

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 3000
min_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 2
memory = '2gb'

[[mounts]]
destination = "/ssd"
source = "volumeapi"
